### ISSUE TITLE
阻止冒泡事件无效

### ISSUE THREAD

**Issue by killdada** [MeCKodo/vue-tap#15]
![qq 20161111171319](https://cloud.githubusercontent.com/assets/16487810/20209970/367d6a74-a832-11e6-8b8c-61204e81de54.png)
 v-tap="gotoProductDetails"
v-tap.prevent="handleAddToCart"  
子级和父级的tap事件都触发了

**Comment by MeCKodo** [comment]
v-tap.prevent 是阻止默认行为。v-tap.stop才是冒泡
