### ISSUE TITLE
a标签下的跳转逻辑是否有点问题?

### ISSUE THREAD

**Issue by JasonOneYuan** [MeCKodo/vue-tap#17]
<a href="http://www.baidu.com" v-tap>如果想要快速跳转直接写v-tap即可不用写任何参数</a>

<a href="aaa" v-tap="{ methods : cant }">can't</a>

这两种情况重叠了 , 后一种的逻辑感觉有点问题 ;
写了methods但没写prevent的情况下 ; 是否应该先执行cant , 然后进行跳转(虽然这在实际应用中很少会用到)

**Comment by MeCKodo** [comment]
之前兼容vue2的时候改动略大,稳当可能没写好,我有空的时候会重新看下哈,3Q
