### ISSUE TITLE
prevent没效

### ISSUE THREAD

**Issue by MTTTM** [MeCKodo/vue-tap#19]
##<#a v-tap.prevent="cant" href="这是无法跳转的">由于写了.prevent 这是无法跳转的<#/a>##
<br/>
这样还是会跳转的

**Comment by MeCKodo** [comment]
请问你是PC还是移动端？具体是怎么写的

**Comment by wcl8955366** [comment]
怎么实现滑动跳转页面的呢？放在手机上测试了一遍，貌似实现不了滑动跳转

**Comment by MeCKodo** [comment]
@wcl8955366 啥叫滑动跳转
