### ISSUE TITLE
延迟定死150毫秒貌似不太科学

### ISSUE THREAD

**Issue by mlinquan** [MeCKodo/vue-tap#21]
我发现源码中延迟设为150毫秒，而且不可更改。
这样貌似不太合理，150毫秒的延迟无法更好的解决移动端300毫秒延迟的问题。
不知道我分析的对不对，但是实际项目测试中绑定事件后很难触发，好点好几次才能触发一次。

**Comment by MeCKodo** [comment]
请问你用啥手机？一般的安卓和iPhone我都测了啊。。150的延迟之前是看alloytouch的，不过最近他好像改了

**Comment by mlinquan** [comment]
华为Mate8。
isTap函数里的判断我改成
return self.time < 300 && Math.abs(tapObj.distanceX) < 20 && Math.abs(tapObj.distanceY) < 20
touched函数改成
function touchend (e, self) {
  var touches = e.changedTouches[0]
  var tapObj = self.tapObj
  self.time = +new Date() - self.time
  tapObj.distanceX = tapObj.pageX - touches.pageX
  tapObj.distanceY = tapObj.pageY - touches.pageY

  if (!isTap(self)) return
  self.handler(e)
}
就完美解决了

**Comment by MeCKodo** [comment]
不会吧？我以前这样写的，mate8还是有bug啊，我记得。。。那时候还拉了一个用户一直让他做测试- -  不过既然你这样可以，我也按你的来好了，可能是安卓系统又不一样了 。 谢啦

**Comment by mlinquan** [comment]
iphone6s plus, iphoen7 plus 也同样有上述问题
按我的方法改后问题完美解决

**Comment by MeCKodo** [comment]
iPhone也有吗？我平时测试机都是iPhone啊。。没有出现这样的问题啊？？？？
这样看来感觉不是setTimeout的问题，不过还是很感谢你的支持
