### ISSUE TITLE
bug，有截图

### ISSUE THREAD

**Issue by treasureDouDou** [MeCKodo/vue-tap#22]
![k_6szkzuetirgqsc_b_65p4](https://cloud.githubusercontent.com/assets/21187862/22141891/0cc2f12a-df2f-11e6-8efe-bc8f2786f575.png)

**Comment by treasureDouDou** [comment]
不加v=if全部显示会触发正常，加了v-if错乱

**Comment by MeCKodo** [comment]
你这个绑定得不都是同个方法吗？

**Comment by treasureDouDou** [comment]
搞得我只有分离了
![image](https://cloud.githubusercontent.com/assets/21187862/22142070/cbe38e84-df2f-11e6-8272-799c8e8a1803.png)
![image](https://cloud.githubusercontent.com/assets/21187862/22142078/d2cfb1fa-df2f-11e6-9c5f-5b95e7ee0de2.png)

**Comment by treasureDouDou** [comment]
@MeCKodo 是同一个方法，但是有参数呀，根据参数来判断东西赛，问题是现在触发的却是v-if=false的！

**Comment by treasureDouDou** [comment]
@MeCKodo 我把方法名称改了！一样的效果，还是触发的上面的

**Comment by MeCKodo** [comment]
如果是@click不会是么？

**Comment by treasureDouDou** [comment]
![qq 20170120165355](https://cloud.githubusercontent.com/assets/21187862/22142417/25526174-df31-11e6-8620-23ca0efa8dac.png)
click正常，你的有问题！

**Comment by MeCKodo** [comment]
可以把测试代码给我一份吗？我测下

**Comment by treasureDouDou** [comment]
加了v-if，带过来的params不正确，不加v-if，全部显示带过来的params正常，你试试

**Comment by doudouyoutangtang** [comment]
`        <ul class="header" v-if="grade == 0">
            <li v-tap="{methods:chooseMenu, name: 'powerUseHami'}">
                <div :class="$route.name == 'powerUseHami'? 'active' : ''">
                    哈密地区
                </div>
            </li>
            <li v-tap="{methods:chooseMenu, name: 'powerUseArea'}">
                <div :class="$route.name == 'powerUseArea'? 'active' : ''">
                    区域统计
                </div>
            </li>
            <li v-tap="{methods:chooseMenu, name: 'powerUseGroup'}">
                <div :class="$route.name == 'powerUseGroup'? 'active' : ''">
                    集团统计
                </div>
            </li>
            <li v-tap="{methods:chooseMenu, name: 'powerUseMerchant'}">
                <div :class="$route.name == 'powerUseMerchant'? 'active' : ''">
                    整机厂商
                </div>
            </li>
        </ul>
        <ul class="header" v-if="grade == 1">
            <li v-tap="{methods:chooseMenu, name: 'groupUse'}">
                <div :class="$route.name == 'groupUse'? 'active' : ''">
                    能源利用
                </div>
            </li>
        </ul>`
`    methods: {
        chooseMenu(params) {
            this.$router.replace({
                name: params.name
            })
        }
    }`

**Comment by treasureDouDou** [comment]
<ul class="header" v-if="grade == 0">
            <li v-tap="{methods:chooseMenu, name: 'powerUseHami'}">
                <div :class="$route.name == 'powerUseHami'? 'active' : ''">
                    哈密地区
                </div>
            </li>
            <li v-tap="{methods:chooseMenu, name: 'powerUseArea'}">
                <div :class="$route.name == 'powerUseArea'? 'active' : ''">
                    区域统计
                </div>
            </li>
            <li v-tap="{methods:chooseMenu, name: 'powerUseGroup'}">
                <div :class="$route.name == 'powerUseGroup'? 'active' : ''">
                    集团统计
                </div>
            </li>
            <li v-tap="{methods:chooseMenu, name: 'powerUseMerchant'}">
                <div :class="$route.name == 'powerUseMerchant'? 'active' : ''">
                    整机厂商
                </div>
            </li>
        </ul>
        <ul class="header" v-if="grade == 1">
            <li v-tap="{methods:chooseMenu, name: 'groupUse'}">
                <div :class="$route.name == 'groupUse'? 'active' : ''">
                    能源利用
                </div>
            </li>
        </ul>
```js
        chooseMenu(params) {
            this.$router.replace({
                name: params.name
            })
        }
```

**Comment by MeCKodo** [comment]
我刚刚更新了@2.2.2 版本 说不定可以了

**Comment by MeCKodo** [comment]
刚刚发布了 @3.0.0版本修复了你这个问题了！！ 不容易啊

**Comment by treasureDouDou** [comment]
@MeCKodo 删除的时候也有毛病，不晓得你知道不，绑定方法，传这条数据的序号，这个方法是删除这条数据，然后从上往下删除还是从下往上删不记得了，还是指向的第一次删除的，弄得我尴尬只能隐藏删除的那一条了

**Comment by MeCKodo** [comment]
这两个bug我都修复了，最新版本3.0.0。
你可以在试试看

**Comment by MeCKodo** [comment]
你可以看下我readme，下面的更新日志

**Comment by treasureDouDou** [comment]
好的

**Comment by MeCKodo** [comment]
你这要是没有bug了麻烦告诉我一声哈！谢谢了
