### ISSUE TITLE
Uncaught TypeError: Property description must be an object: undefined

### ISSUE THREAD

**Issue by treasureDouDou** [MeCKodo/vue-tap#25]
![image](https://cloud.githubusercontent.com/assets/21187862/22281739/764a60e6-e313-11e6-9657-8323d4e6c474.png)

**Comment by treasureDouDou** [comment]
昨天npm下来的可用，今天npm下来的报这个，弄了一天，最后把你git上的js手动下下来import进来才正常

**Comment by MeCKodo** [comment]
sorry ，我现在就看下

**Comment by MeCKodo** [comment]
已更新
