### ISSUE TITLE
数组列表改变后，v-tap的传值有个BUG

### ISSUE THREAD

**Issue by taoliujun** [MeCKodo/vue-tap#26]
`        <a href="#" v-for="value of cacheRecord" v-tap.prevent="{methods:recordSearch,value:value}">{{value}}</a>
`

cacheRecord是一个数组，大概格式是[12,35,98,13]，点击第一个a标签，这个时候recordSearch方法里打印的value值是12。

第一次点击后，将cacheRecord改成为[18,12,35,98,13]，点击第一个a标签，这个时候recordSearch方法里打印的value值仍是12。(期望值是18)

用@click替换v-tap，达到期望

**Comment by MeCKodo** [comment]
谢谢反馈，我这两天会看下！

**Comment by sarazhang123** [comment]
我也遇到相同的问题

**Comment by MeCKodo** [comment]
可以麻烦给我看下 recordSearch的具体实现吗？

**Comment by MeCKodo** [comment]
@taoliujun 
```js
test() {
  		this.cacheRecord.unshift(18);
  		console.log(this.cacheRecord[0]);
    },
```
我是这样的测试代码是正常的，不知道你是怎么写的。我是vue2.0

**Comment by marsprince** [comment]
确实是BUG：
例：number in even(numbers) 
 even(numbers){
            return numbers.filter(function (number) {
                return number%2===0
            })
        },

v-tap不会拿到偶数值，而会拿到原始值，将directive的绑在update上就可以解决了，具体的没研究

**Comment by marsprince** [comment]
@MeCKodo 所有mounted和update里的改变都是无效的，应该和你的绑定有关，我把v-tap绑在update上就没问题了，你绑在bind上就不会变了

**Comment by MeCKodo** [comment]
@marsprince  有联系方式吗？我可以具体了解下bug，然后一起解决吗 :）

**Comment by marsprince** [comment]
@MeCKodo QQ1018641956

**Comment by MeCKodo** [comment]
BUG已修复，可以看repo中的list-test.html
@taoliujun @sarazhang123 @zlxbuzz @zgayjjf @marsprince
