### ISSUE TITLE
移动端测试可以为什么chrome 没有任何反映？

### ISSUE THREAD

**Issue by vonch** [MeCKodo/vue-tap#27]
<li class="model4" v-tap='go_market'>

这样的写法在手机上可以，但是在chrome 下模拟移动端却没有任何反映呢？

**Comment by vonch** [comment]
忘记说了环境
vue 1.0

**Comment by MeCKodo** [comment]
理论上来说不可能啊。。我测试过了，谷歌也是可以的

**Comment by MeCKodo** [comment]
我又测试了一次，我这是正常的，还有建议js不要用下划线，用驼峰命名比较好

**Comment by vonch** [comment]
时好时坏很奇怪啊！~10次点击80次不行的，有两次可以。只是在chrome 下不行，移动端是好的。

**Comment by MeCKodo** [comment]
你可能装了假谷歌？？ 我一直可以。。
