### ISSUE TITLE
The param of directive "v-tap" must be a function!

### ISSUE THREAD

**Issue by vonch** [MeCKodo/vue-tap#28]
我在非原生link 标签添加  v-tap 就会报 The param of directive "v-tap" must be a function! 而且没有任何效果。

**Comment by MeCKodo** [comment]
你用router-link吗？

**Comment by MeCKodo** [comment]
我是vue2.0版本的，测试了router-link 没有问题
`    <router-link v-tap to="/foo">go to foo</router-link>
`

**Comment by MeCKodo** [comment]
非a标签和router-link的话不能直接v-tap，你必须要带方法啊。。。因为你又不跳转
