### ISSUE TITLE
动态dom 如何写 tap?

### ISSUE THREAD

**Issue by vonch** [MeCKodo/vue-tap#29]
动态dom 如何写 tap?

**Comment by MeCKodo** [comment]
show 代码

**Comment by vonch** [comment]
vue 结合 jq 用的插件写法；

例如：

<template>
<div @click='test'>
    ....
</div>
</template>

function a(link,val){
    var html = '\<a href = " '+link+' "\>'+val+'\</a\>';
    $('body').append(html);
}


var v = new vue({
....
methods : {
    test : function(){
        a('http://www.baidu.com/','测试');
    }
}
})

**Comment by MeCKodo** [comment]
这不行的，只有vue的才能用v-tap。因为v-tap是指令
