### ISSUE TITLE
我的v-tap指令不能识别，vue2.0

### ISSUE THREAD

**Issue by summer-yyyn** [MeCKodo/vue-tap#33]
[Vue warn]: Failed to resolve directive: tap 
(found in anonymous component - use the "name" option for better debugging messages.)

**Comment by MeCKodo** [comment]
你组件没搞好吧。。

**Comment by summer-yyyn** [comment]
main.js:

import vuetap from 'v-tap';

Vue.use(VueAxios, axios, vuetap);


组件里面：

<div class="btn" v-tap="{methods : addNewAddress}" v-show="hasaddress">添加新地址</div>
我是照着你的文档写的呀，搞了一上午了，求指导~~~

**Comment by summer-yyyn** [comment]
<div class="btn" v-tap="{methods : addNewAddress}" v-show="hasaddress">添加新地址</div>

**Comment by summer-yyyn** [comment]
/ <div class="btn" v-tap="{methods : addNewAddress}" v-show="hasaddress">添加新地址</div>/

**Comment by summer-yyyn** [comment]
`<div class="btn" v-tap="{methods : addNewAddress}" v-show="hasaddress">添加新地址</div>`

**Comment by MeCKodo** [comment]
这样也具体不知道是什么问题。。vue2.0绝对可以用，我自己都用
