### ISSUE TITLE
在使用v-if时事件绑定错误！~

### ISSUE THREAD

**Issue by luandapipi** [MeCKodo/vue-tap#34]
`<div class="right" v-tap="{ methods :sendOrder}" v-if="canBuy">
          确认订购
        </div>
        <div class="right disabled" v-else>
          确认订购
        </div>`
在当canBuy变量为false时，v-tap方法绑定到了另外一个div上~！

**Comment by MeCKodo** [comment]
绑定到了v-else上吗？

**Comment by luandapipi** [comment]
对的，如果一开始绑定 if 的那个按钮，在条件改变后 v-else的按钮同样有tap事件

**Comment by MeCKodo** [comment]
可否留个QQ一起帮忙做下测试？然后我晚上修一下

**Comment by luandapipi** [comment]
172738011 @MeCKodo
