### ISSUE TITLE
router-link 上如何写 v-tap

### ISSUE THREAD

**Issue by Andykeh** [MeCKodo/vue-tap#37]
rt 直接写 v-tap 点击页面就刷新了 state全丢失，该如何使用？

**Comment by luuman** [comment]
绑定事件跳转咯！this.$router.push({ path: text })

**Comment by Andykeh** [comment]
@luuman 那意思是不能用router-link 的方式了？

**Comment by MeCKodo** [comment]
你想怎么用。。。router-link 最多 加个快速跳转吧？
