### ISSUE TITLE
是否可以介绍一下和FastClick js的区别？

### ISSUE THREAD

**Issue by Jiiiiiin** [MeCKodo/vue-tap#44]
如题：
如果
`document.addEventListener('DOMContentLoaded', function () {
    if (window.FastClick) window.FastClick.attach(document.body);
}, false);
`
这样就能解决穿透，那么我们为何放弃直接写@click简写，有什么理由？

**Comment by MeCKodo** [comment]
我是浪漫主义，于是造了v-tap
