### ISSUE TITLE
v-tap只是用来stop或prevent事件时,希望可以更简便些

### ISSUE THREAD

**Issue by jy90719** [MeCKodo/vue-tap#49]
您好,目前在使用该插件时,遇到个小问题,就是如果我只是想用来v-tap.prevent或stop时,必须要传入一个methods(如:v-tap.stop="{methods:functionName}")才可以,否则会报错,希望可以支持直接v-tap.stop或v-tap.prevent 这样在使用时更方便些,谢谢

**Comment by MeCKodo** [comment]
可以说一些具体场景吗？感觉没必要啊。。

**Comment by jy90719** [comment]
就是在我只需要给dom注册某个事件为的是阻止冒泡或阻止浏览器默认行为的时候,这个时候我并不需要注册事件监听函数的,这个时候如果只需要加个v-tap.prevent/stop就可以的话 就会感觉很方便

**Comment by MeCKodo** [comment]
不好意思，不加这个需求，跟v-tap无关。v-tap专注于tap事件，未来应该会新增longtap事件。
