### ISSUE TITLE
无法获取绑定的元素

### ISSUE THREAD

**Issue by turbe** [MeCKodo/vue-tap#5]
代码：
'''
＜div  v-tap=“helloClick”＞
＜div ＞
＜div ＞
＜/div＞
＜/div＞
＜/div＞
'''
e.currentTarget结果是null

**Comment by turbe** [comment]
多层div中，在最顶层绑定v-tap指令后，就是获取不到e.currentTarget

**Comment by MeCKodo** [comment]
就问你想获取谁？？？

**Comment by MeCKodo** [comment]
我更新了demo，你可以看下到底想获取谁
