### ISSUE TITLE
IOS设备上，fixed的button，滑动一段距离无法响应点击事件

### ISSUE THREAD

**Issue by sarazhang123** [MeCKodo/vue-tap#58]
以下是我的测试链接
http://7xpg8c.com1.z0.glb.clouddn.com/v-tap-test/fixed-button.html?a=2

在IOS设备的微信中打开以上链接，往下滑动一段距离，使滚动条离开顶部，此时点击button，不会弹出alert。

以下为源代码：
```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>测试fixed btutton在ios上无法点击的问题</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
	<style>
		body {
			color: #fff;
		}

    .demo {
      height: 1000px;
      background-color: bisque;
    }

    .fixed-bottom {
      position: fixed;
      left: 0;
      right: 0;
      bottom: 0;
      width: 100%;
      height: 50px;
    }

    .fixed-top {
      position: fixed;
      left: 0;
      right: 0;
      top: 0;
      width: 100%;
      height: 50px;
    }
	</style>
</head>
<body>
<button class="fixed-top" v-tap="clickMe('点击顶部按钮了！')">我是固定在顶部的button</button>
<div class="demo">
</div>
<button class="fixed-bottom" v-tap="clickMe('点击底部按钮了！')">我是固定在底部的button</button>

<script src="./vue.js"></script>
<script src="./vue-tap.js"></script>
<script>

  new Vue({
    el: "body",
    data: {
    },
    methods: {
      clickMe: function (message) {
        alert(message)
      }
    }
  });
</script>
</body>
</html>

```

**Comment by sarazhang123** [comment]
看来这是一个ios的bug...

https://stackoverflow.com/questions/8809706/ios-5-safari-bug-with-html-touch-events-on-positionfixed-div

**Comment by sarazhang123** [comment]
@MeCKodo

**Comment by MeCKodo** [comment]
我系统是10.3.3的 iPhone6s 
在你的链接是可以触发的0 0

**Comment by sarazhang123** [comment]
@MeCKodo 需要在ios微信中打开，并且`向上滑动页面`，方可重现该bug。因为我这边的iphone5c, iphone6, iphone6s, iphone6s plus都不能触发点击，集体中招。你可以再试一试...

**Comment by MeCKodo** [comment]
我复制了你的链接，然后再微信里打开的。
操作过程，进入页面，直接点击可以alert
滚动页面，分别滚动一点点滚动条，滚动一半滚动条，随意上下滚动，之后点击按钮都可以alert
还有你测试最好不要写alert测试，最好是append一个dom到页面上来测。

**Comment by sarazhang123** [comment]
我又更新了一下测试链接，再在微信中打开一下，这次是append节点的，难道你身边的其他ios设备打开没有和我一样的问题，奇怪了...

 http://7xpg8c.com1.z0.glb.clouddn.com/v-tap-test/fixed-button.html?a=3

**Comment by MeCKodo** [comment]
你看下版本吧。。我刚刚更新了最新微信也OK，点击后 append很快
我ios系统是10.3.3的
ios11的系统有很多的bug，不管是js还是样式都会有bug

**Comment by sarazhang123** [comment]
好吧，我们这边的ios系统都升级到11了，看来11问题比较多，那关于fixed的元素，还是只能用`v-on:click`了，不纠结了...

**Comment by MeCKodo** [comment]
不好意思，不仅是我这个问题，ios11还有很多别的蜜汁bug。
good luck

**Comment by sarazhang123** [comment]
thx
