### ISSUE TITLE
touchend中为什么要延迟执行handler

### ISSUE THREAD

**Issue by stonelee** [MeCKodo/vue-tap#6]
代码在：https://github.com/MeCKodo/vue-tap/blob/master/vue-tap.js#L104

```
setTimeout(function() {
    self.handler(e);
},150)
```

为什么要延迟150ms才执行，如果不加这个延迟，可以更快的进行跳转。

**Comment by MeCKodo** [comment]
防止点透和安卓可能有的无法触发的bug
