### ISSUE TITLE
当有input 获焦时，tap 点击事件不会让Input失焦

### ISSUE THREAD

**Issue by wuchuguang** [MeCKodo/vue-tap#7]
<input name="test" value="" />这里获焦，
<button v-tap="tap_event">Button </button>这里点击，input还是获焦状态．

**Comment by MeCKodo** [comment]
有demo吗

**Comment by toMatthew** [comment]
我也遇到这样的情况，就在点击输入框输入文字的时候，然后点击提交，焦点在还输入框，手机键盘没有隐藏。正常应该是buttom获焦，手机键盘隐藏的。

**Comment by mkanako** [comment]
我也发现了，安卓确实有这个问题，ios就没事

**Comment by wxfjq313** [comment]
<ul>
          
          <li v-for="item,index in reasons" :key="index" v-tap="{methods:itemChecked, index:index}">
            <input type="radio" class="radio-input" :value="item" v-model="chooseReason">
            <span class="radio-core" ></span>

            <input v-if="index == reasons.length-1" type="text" class="radio-text" v-model="chooseReason1"
                   placeholder="输入其他原因" @input="handleInputChanged">
            <span v-else class="radio-label">{{item}}</span>
          </li>
        </ul>

input 无法获取焦点了

**Comment by wxfjq313** [comment]
`    <ul>`
          `<!--v-tap="{methods:itemChecked,index:index}"-->`
          `<li v-for="item,index in reasons" :key="index" v-tap="{methods:itemChecked, index:index}">`
           ` <input type="radio" class="radio-input" :value="item" v-model="chooseReason">`
          `  <span class="radio-core" ></span>`
            `<input v-if="index == reasons.length-1" type="text" class="radio-text" v-model="chooseReason1"`
                  ` placeholder="输入其他原因" @input="handleInputChanged">`
            `<span v-else class="radio-label">{{item}}</span>`
         `</li>`
        `</ul>`

input 无法获取焦点 输入内容

**Comment by MeCKodo** [comment]
@wxfjq313  好的，下个版本就会修复这个问题
